# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Check test-vectors

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: setup
        run: |
          npm install -g npm@7.13.0
          npm run setup
          cd test
          npx hardhat compile
          cd ..
      - name: eslint
        run: npm run eslint
      - name: check no-data state-transition
        run: npm run test:st:no-data
      - name: check calldata state-transition
        run: npm run test:st:calldata
      - name: check smt
        run: npm run test:smt
      - name: check contracts
        run: npm run test:contracts
      - name: check mt bridge
        run: npm run test:mt:bridge
      - name: check test e2e
        run: npm run test:e2e